import pandas as pd
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(current_dir, 'data', 'pokemon.csv')
df = pd.read_csv(csv_path)

print("=" * 60)
print("DATA TYPE CONVERSION")
print("=" * 60)

print("\n" + "=" * 50)
print("1. CHECK CURRENT DTYPES")
print("=" * 50)
print(df.dtypes)

print("\n" + "=" * 50)
print("2. CONVERT TO STRING (astype)")
print("=" * 50)
df['HP_String'] = df['HP'].astype(str)
print(df[['HP', 'HP_String']].head(3))
print("HP dtype:", df['HP'].dtype)
print("HP_String dtype:", df['HP_String'].dtype)

print("\n" + "=" * 50)
print("3. CONVERT TO INTEGER")
print("=" * 50)
df_float = pd.DataFrame({'Value': ['10', '20', '30']})
df_float['Value_Int'] = df_float['Value'].astype(int)
print(df_float)
print(df_float.dtypes)

print("\n" + "=" * 50)
print("4. CONVERT TO FLOAT")
print("=" * 50)
df['HP_Float'] = df['HP'].astype(float)
print(df[['HP', 'HP_Float']].head(3))
print(df[['HP', 'HP_Float']].dtypes)

print("\n" + "=" * 50)
print("5. CONVERT WITH ERRORS (to_numeric)")
print("=" * 50)
df_mixed = pd.DataFrame({'Value': ['10', '20', 'invalid', '30']})
df_mixed['Value_Numeric'] = pd.to_numeric(df_mixed['Value'], errors='coerce')
print(df_mixed)
print("Note: 'invalid' became NaN")

print("\n" + "=" * 50)
print("6. CONVERT TO CATEGORY (MEMORY EFFICIENT)")
print("=" * 50)
print("Before conversion:")
print(f"Type dtype: {df['Type'].dtype}")
print(f"Memory: {df['Type'].memory_usage(deep=True)} bytes")

df['Type_Category'] = df['Type'].astype('category')
print("\nAfter conversion:")
print(f"Type_Category dtype: {df['Type_Category'].dtype}")
print(f"Memory: {df['Type_Category'].memory_usage(deep=True)} bytes")

print("\n" + "=" * 50)
print("7. CONVERT TO DATETIME")
print("=" * 50)
df_dates = pd.DataFrame({'Date': ['2024-01-01', '2024-01-02', '2024-01-03']})
df_dates['Date_Datetime'] = pd.to_datetime(df_dates['Date'])
print(df_dates)
print(df_dates.dtypes)

print("\n" + "=" * 50)
print("8. CONVERT TO BOOLEAN")
print("=" * 50)
df['Is_Strong'] = (df['Attack'] > 80).astype(bool)
print(df[['Name', 'Attack', 'Is_Strong']].head(10))

print("\n" + "=" * 50)
print("9. CONVERT MULTIPLE COLUMNS")
print("=" * 50)
df_convert = df[['HP', 'Attack', 'Defense']].astype(float)
print(df_convert.dtypes)

print("\n" + "=" * 50)
print("10. INFER BEST DTYPE (convert_dtypes)")
print("=" * 50)
df_infer = df.copy()
df_infer = df_infer.convert_dtypes()
print(df_infer.dtypes)
