import pandas as pd
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(current_dir, 'data', 'pokemon.csv')
df = pd.read_csv(csv_path)

print("=" * 60)
print("PIVOT TABLES AND RESHAPING")
print("=" * 60)

print("\n" + "=" * 50)
print("1. PIVOT TABLE - BASIC")
print("=" * 50)
pivot = df.pivot_table(values='HP', index='Type', aggfunc='mean')
print(pivot)

print("\n" + "=" * 50)
print("2. PIVOT TABLE - MULTIPLE AGGREGATIONS")
print("=" * 50)
pivot = df.pivot_table(values='HP', index='Type', aggfunc=['mean', 'max', 'min'])
print(pivot)

print("\n" + "=" * 50)
print("3. PIVOT TABLE - MULTIPLE VALUES")
print("=" * 50)
pivot = df.pivot_table(values=['HP', 'Attack'], index='Type', aggfunc='mean')
print(pivot)

print("\n" + "=" * 50)
print("4. GROUPBY (SIMILAR TO PIVOT)")
print("=" * 50)
grouped = df.groupby('Type')[['HP', 'Attack', 'Defense']].mean()
print(grouped)

print("\n" + "=" * 50)
print("5. MELT - WIDE TO LONG FORMAT")
print("=" * 50)
df_wide = df[['Name', 'HP', 'Attack', 'Defense']].head(3)
print("Wide format:")
print(df_wide)
print("\nLong format (melted):")
df_long = df_wide.melt(id_vars='Name', var_name='Stat', value_name='Value')
print(df_long)

print("\n" + "=" * 50)
print("6. PIVOT - LONG TO WIDE FORMAT")
print("=" * 50)
df_pivoted = df_long.pivot(index='Name', columns='Stat', values='Value')
print(df_pivoted)

print("\n" + "=" * 50)
print("7. STACK - COLUMNS TO ROWS")
print("=" * 50)
df_sample = df[['Name', 'HP', 'Attack']].head(2).set_index('Name')
print("Original:")
print(df_sample)
print("\nStacked:")
df_stacked = df_sample.stack()
print(df_stacked)

print("\n" + "=" * 50)
print("8. UNSTACK - ROWS TO COLUMNS")
print("=" * 50)
print("Unstacked:")
df_unstacked = df_stacked.unstack()
print(df_unstacked)

print("\n" + "=" * 50)
print("9. TRANSPOSE - FLIP ROWS AND COLUMNS")
print("=" * 50)
df_sample = df[['Name', 'HP', 'Attack', 'Defense']].head(3).set_index('Name')
print("Original:")
print(df_sample)
print("\nTransposed:")
print(df_sample.T)

print("\n" + "=" * 50)
print("10. CROSSTAB - FREQUENCY TABLE")
print("=" * 50)
df['HP_Category'] = pd.cut(df['HP'], bins=[0, 50, 80, 150], labels=['Low', 'Medium', 'High'])
crosstab = pd.crosstab(df['Type'], df['HP_Category'])
print(crosstab)
